default_stages: [commit, push]
exclude: "^CHANGELOG.md$"

repos:
  - repo: https://github.com/psf/black
    rev: 24.2.0
    hooks:
      - id: black
        args:
          - "--line-length=120"
          - "--target-version=py311"
        types: [python]

  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.10.1
    hooks:
      - id: isort
        args:
          - "--line-length=120"
          - "--profile=black"

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.1.0
    hooks:
      - id: prettier

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: no-commit-to-branch

  - repo: https://github.com/codespell-project/codespell
    rev: v2.2.6
    hooks:
      - id: codespell

  - repo: https://github.com/snakemake/snakefmt
    rev: v0.10.0
    hooks:
      - id: snakefmt
        args:
          - "--line-length=120"

  - repo: local
    hooks:
      - id: snakemake_linter
        name: snakemake_linter
        entry: snakemake -c1 --lint --directory .tests/ --snakefile workflow/Snakefile
        language: python
      - id: snakemake_dry_run
        name: snakemake_dry_run
        entry: snakemake -c1 -n --directory .tests/ --snakefile workflow/Snakefile
        pass_filenames: false
        always_run: true
        language: python
